title: Megus
email: megus.sugem@gmail.com
author: Megus
description: "Personal website of Roman "Megus" Petrov, a programmer and a musician."
baseurl: ""
url: "https://megus.org"

twitter:
  card: summary
  username: sugem

#logo: /path/to/logo.png

exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock

header_pages:
  - about.md
  - portfolio.html
  - music.html

collections:
  projects:
    output: true

show_excerpts: true
excerpt_separator: <!--more-->

google_analytics: UA-104711057-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
